### ISSUE TITLE
Verify Helpline Numbers ☎️

### ISSUE THREAD

**Issue by theapache64** [teamxenox/CoDoc19#1]
I've generated a `JSON` [contact list](https://github.com/teamxenox/CoDoc19/blob/master/india_helpline.json) file from this [PDF](https://www.mohfw.gov.in/pdf/coronvavirushelplinenumber.pdf). It contains central helpline number for corona-virus in India. 

TASK : Check if the numbers are valid phone numbers. Also, it'd better if you can crosscheck the numbers with Google.

**Comment by whitebumblebee** [comment]
All the numbers verified as of commit [ d88d8f7](https://github.com/teamxenox/CoDoc19/commit/d88d8f7b02af5d30fc6553a3ebf89a52b31ceb5a)
