### ISSUE TITLE
Make doctor more friendlier

### ISSUE THREAD

**Issue by theapache64** [teamxenox/CoDoc19#2]
[Doctor](https://github.com/teamxenox/CoDoc19/blob/master/src/main/kotlin/com/teamxenox/codoc19/core/features/test/Doctor.kt) is responsible to run the corona-test. During the test, he should be nice to patients. 

**TASK**: Make the conversation more friendlier by updating the questions and emojis. 

eg: 
- `Do you have fever?` can be changed to `Do you have fever? 🤒`.
- `Don't worry. You're just having common flu` can be changed to `Alright. It seems like you're just having the common flu. Nothing to worry 😇`

**HINT**: 

- Find the questions and it's replies from [Doctor.kt](https://github.com/teamxenox/CoDoc19/blob/master/src/main/kotlin/com/teamxenox/codoc19/core/features/test/Doctor.kt) file and start editing it.
- You don't have to compile the project. You can use any text editor.

**Comment by whitebumblebee** [comment]
Added some emojis and some modifications to few questions to make doctor friendlier.
fixed with commit [30c9c2f](https://github.com/teamxenox/CoDoc19/commit/30c9c2f75bf52651bb42ddc2e0c1c6c67bc81607)
