### ISSUE TITLE
wrong number format

### ISSUE THREAD

**Issue by zaunermax** [teamxenox/CoDoc19#27]
First off, awesome bot!

When asking for the stats, the numbers are formatted the wrong way. I think it has something to do with the good old comma and dot separation 🤔 

for me, the numbers look like this:

![grafik](https://user-images.githubusercontent.com/15246773/78510349-db84cc80-7794-11ea-96d6-b2653eeb9e41.png)

I am in Austria and we of use `,` for comma notation, not `.` so I am guessing that's the problem.

**Comment by theapache64** [comment]
HI @zaunermax , 

Thank you so much for your feedback.
Actually, it's a comma. As the font size is small,I think it's not that clear.

**Comment by zaunermax** [comment]
Oh the problem is not that there is a comma, but every number starting from millions is formatted the wrong way.

It should be `1,268,821` but in my case it is formatted `12,68,821` - so the comma is shifted to the right one position.

Also when looking at the active cases, there seems to be a problem with the comma position

**Comment by theapache64** [comment]
Alright. As we're from India, the comma separation is a [bit different here](https://en.wikipedia.org/wiki/Indian_numbering_system). Anyway, we've decided to change it to the global format. :) Thank you for reporting this issue @zaunermax :+1:

**Comment by zaunermax** [comment]
Ohhh I see, I really did not know this - the more you know...

**Comment by theapache64** [comment]
@zaunermax It's fixed :) You may check now.
